macro(set_cxx_standard version)
	if (CMAKE_VERSION VERSION_LESS "3.1")
		if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
			set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++${version}")
		endif ()
	else ()
		set (CMAKE_CXX_STANDARD ${version})
	endif ()
endmacro(set_cxx_standard)
